### ISSUE TITLE
Suggested improvements to sigma_cont

### ISSUE THREAD

**Issue by AstroRobin** [MBravoS/splotch#1]
For generating contoured lines on plots with sigma_cont:

 - It would good to merge this sigma_cont function with a function that also does filled contours if some "fill" flag is set. This will require some tweaking of the way you treat levels as in the filled case, they need to represent bounds of the filled regions.

- The default contour labels (clabel) could be set to the string versions of the percentiles given quite easily by multiplying by 100 and converting to a string. Would avoid mislabelled contours.

**Comment by MBravoS** [comment]
Thanks for the suggestions. The second one is implemented now in _0.2.3_, together with a change from fractions to percentages for the values that `percent` accepts. The other one should be added in _0.2.4_.

**Comment by MBravoS** [comment]
Filled option added as of version **0.5.0**.
