### ISSUE TITLE
hist_1d w/ bin_type='equal' breaks if bins=len(data)

### ISSUE THREAD

**Issue by AstroRobin** [MBravoS/splotch#11]
hist_1d(data, bin_type='equal') will throw an error if the number of bins is strictly greater than the number of data points. Whilst it probably makes sense that the code should break on this usage, the error being thrown is a bit confusing. We should throw our own exception if len(bins) > len(data).

**Comment by MBravoS** [comment]
An error is raised for this case as of version 0.5.1.0.
