### ISSUE TITLE
return of hist()

### ISSUE THREAD

**Issue by AstroRobin** [MBravoS/splotch#12]
When parsing in only a single data set, the return of bin_edges/n from splotch.hist() is in the form of  [[x x x x x]], where it seems more sensible to have this come out in the format [x x x x x] in the case where only one data set is given.

Also, we should probably align ourselves with the matplotlib standards which returns (in this order): n, bins (i.e. edges), patches. The last one here is actually very useful to return afterwards.

**Comment by MBravoS** [comment]
Order of the returns now follows matplotlib practice from 0.3.0.1. Rest of improvements to be made in future releases.

**Comment by MBravoS** [comment]
The return when given one data set is now the expected [x x x x x] as of version 0.5.1.0.
