### ISSUE TITLE
Colour bar access for customisation

### ISSUE THREAD

**Issue by MBravoS** [MBravoS/splotch#19]
Currently is impossible for the user to modify the colour bar made with any of the splotch plotting functions that produce one, as the variable pointing to the object exist only internally to the function.  A possible solution is to give the option to return the colour bar object, so that is accesible to the user.

**Comment by AstroRobin** [comment]
@MBravoS, this is now possible with the addition of `splotch.colorbar()` in #20 . We can implement this function by default into our other functions requiring a colorbar. If the user wishes to customise beyond defaults, they could instead explicitly make use of splotch.colorbar().
