### ISSUE TITLE
brokenplot() sometimes uses different formatting between axis ticks

### ISSUE THREAD

**Issue by AstroRobin** [MBravoS/splotch#27]
Depending on the range and frequency of ticks on the axes either side of the break, the ticks will sometimes be shown as floats and integers. `brokenplot()` should be modified so that consistent tick formatting is used across both axes.

**Comment by MBravoS** [comment]
What is the status of this issue? Does it still remain or has it been fixed?

**Comment by AstroRobin** [comment]
With the updates made to `brokenplot()`, this occurs far less often and only when the ranges of data are so >6 orders of magnitude different when scientific notation kicks in. This is not really a bug as that's kind of the expected behaviour. Happy to close this issue for now.
