### ISSUE TITLE
splotch.hist() does not display beginning/ending lines

### ISSUE THREAD

**Issue by AstroRobin** [MBravoS/splotch#40]
In splotch.hist(), when 'hist_type' = 'step', the resulting line does not show the beginning/ending lines which connect the first/last bin values down to the bottom of the axis (i.e. 0). This creates for a floating horizontal line on the left and right of the plot.

**Comment by MBravoS** [comment]
Fixed as of version 0.5.1.0, though notice it only applies when `ylog=False`, as I can't think of an easy solution when a log scale is used.

**Comment by AstroRobin** [comment]
Cool, happy with this solution, when `ylog=True`, there isn't yet a good solution that I can think of.
