### ISSUE TITLE
hist2D problem

### ISSUE THREAD

**Issue by Matthew-Wilkinson** [MBravoS/splotch#47]
>>> a = np.random.random(1000)
>>> b = np.random.random(1000)
>>> splt.hist2D(a,b)
Traceback (most recent call last):
  File "<ipython-input-70-6bfa285d9a4c>", line 1, in <module>
    splt.hist2D(a,b)
  File "/home/matt/anaconda3/lib/python3.7/site-packages/splotch/plots_2d.py", line 632, in hist2D
    _,_,counts = basehist2D(x,y,c,bin_type,bins,scale,dens,'count',xlog,ylog)
  File "/home/matt/anaconda3/lib/python3.7/site-packages/splotch/base_func.py", line 76, in basehist2D
    Z=binned_statistic_2d(x_temp,y_temp,c,statistic=cstat,bins=[x_bins_hist,y_bins_hist])[0]
  File "/home/matt/anaconda3/lib/python3.7/site-packages/scipy/stats/_binned_statistic.py", line 347, in binned_statistic_2d
    expand_binnumbers=expand_binnumbers)
  File "/home/matt/anaconda3/lib/python3.7/site-packages/scipy/stats/_binned_statistic.py", line 518, in binned_statistic_dd
    if not np.isfinite(values).all() or not np.isfinite(sample).all:
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by MBravoS** [comment]
I'm not able to re-create this issue with `numpy 1.17.2`, `scipy 1.3.1` and `splotch 0.4.6.8` (latest available in PyPI). What versions of each are you using? Furthermore, trying to reproduce a error that appeared from a random data set is hard, do you know of any seed values that would trigger the error? Even better if you could share the exact values that cause the issue, as from my understanding not even the using the same seed value would guarantee replication of the exact values (see [NumPy Enhancement Proposal #19](https://numpy.org/neps/nep-0019-rng-policy.html)).

**Comment by Matthew-Wilkinson** [comment]
The issues isn't specific to the random numbers. Just for sanity I did  `np.random.seed(1)` and got the same error. I'm on `numpy 1.18.1`, `scipy 1.4.1` and `splotch 0.4.6.8` (this is a pretty much out of the box anaconda install).

**Comment by MBravoS** [comment]
The issue came from a poor use on our side of `binned_statistics()` (passing non-numeric values in the `c` input), which was functional under previous versions of SciPy, but now raises an error for versions 1.4.0 and newer. Fixed as of `splotch 0.4.6.9`.
