### ISSUE TITLE
Handling legend handles in contourp()

### ISSUE THREAD

**Issue by AstroRobin** [MBravoS/splotch#50]
In version 0.5.0.0, when reverting to automatic handling of legend handles, the call to `temp_ax=gca().get_children` will likely return all children in the current axis which may include previous plot objects unrelated to the contour lines. This should be changed to retrieve the outputs of `contour()` or `contourf()` and use these to extract the linestyles and colours.

**Comment by MBravoS** [comment]
Fixed now on the current 0.5.0.0 on the _devel_ branch.
