### ISSUE TITLE
Renaming of 'plabel'

### ISSUE THREAD

**Issue by AstroRobin** [MBravoS/splotch#51]
Many functions still use `plabel` to define the label of the plotting object. This should be changed to simply 'label' to be consistent with matplotlib and other splotch functions; with exception to the `plabel` used in `splotch.contourp()` which denotes the percent labels and differentiates from `clabel` for the colorbar.

**Comment by AstroRobin** [comment]
Fixed as of version 0.5.0.1

**Comment by AstroRobin** [comment]
Now that contourp() does not create a colorbar inside the function, there is no distinction between a `plabel` (percentile label) and a `clabel` (colourbar label, which may be confused with contour label?). I think we should change `plabel` to `label` to be consistent with all matplotlib and splotch functions.

A deprecation warning can be raised to handle references to plabel for the time being.

**Comment by MBravoS** [comment]
This was fixed on version 0.5.10.0.
