### ISSUE TITLE
Colorbar doesn't work if its not connected to an existing axes

### ISSUE THREAD

**Issue by MBravoS** [MBravoS/splotch#54]
Matplotlib's version allows to generate a color bar without being linked to an existing axes by passing a `ScalarMappable`, but that functionality is not present on our function to make color bars. Perhaps it would be good to work this out together with issue #41.

**Comment by AstroRobin** [comment]
The following works in the splotch colorbar function:

```
fig = plt.figure()

splt.colorbar(mpl.cm.ScalarMappable(norm=None, cmap='plasma'))

plt.show()
```

Does this solve the issue above?

**Comment by MBravoS** [comment]
I assume that the issue got fixed with one of the changes in our colour bar since I raised this issue, as it does seem to work, so I'll close this.
