### ISSUE TITLE
splt.statband() does not accept function for stat_low/stat_high

### ISSUE THREAD

**Issue by AstroRobin** [MBravoS/splotch#57]
There is a bug in splt.statband() if a function is given for the 'stat_low' or 'stat_high' parameters. This is caused by the following line:
`elif 'std' in band_stat[i] and len(band_stat[i].replace('std',''))>0:`

Because a function cannot be iterated over when checking if 'std' in `band_stat[i]`. In order to get around this, we could add a check prior of the form:

`elif callable(band_stat[i]):`

**Comment by MBravoS** [comment]
This was fixed in 0.5.4.2.
