### ISSUE TITLE
Move towards using in-built splotch.colorbar() in splotch functions

### ISSUE THREAD

**Issue by AstroRobin** [MBravoS/splotch#65]
Currently, functions such as splotch.scatter( ) use the default matplotlib colorbar function, which has some annoying downsides such as compressing the axis attached to the colorbar. This problem is negated by splotch.colorbar(), so we should move toward using this function when triggering colorbar generation inside of a 2D plotting function.

I also personally don't like using `clabel` as a trigger for generating a colorbar, it's a bit too abstract, especially in the case where one does not want a colorbar label for example.

**Comment by MBravoS** [comment]
> Currently, functions such as splotch.scatter( ) use the default matplotlib colorbar function, which has some annoying downsides such as compressing the axis attached to the colorbar. This problem is negated by splotch.colorbar(), so we should move toward using this function when triggering colorbar generation inside of a 2D plotting function.
I'll need to re-familiarise myself with our colour bar function/class, if it's ready we should make the move.
> I also personally don't like using `clabel` as a trigger for generating a colorbar, it's a bit too abstract, especially in the case where one does not want a colorbar label for example.
Fair enough, though I would think that just passing a string to `clabel` should be enough to trigger a colour bar. Having both `cbar` and `clabel` options with that redundancy could work, but perhaps there is a cleaner option?

**Comment by AstroRobin** [comment]
I suppose it depends on whether we believe there are use cases for a colorbar with no label, despite the obvious scientific injustice in doing this. To me it's more the fact that it seems to be an abstract way to trigger it, as a user you would simply just have to "know" about this feature rather than it be intuitive.

Potentially, the middle ground is that both a `cbar=True` or `clabel="Test"` are sufficient to trigger a colorbar?

**Comment by MBravoS** [comment]
I'm not sure there is a reason that passing a colour bar label _shouldn't_ trigger drawing the colour bar, given that one of our core aims is convenience. As for the use of colour bars without labels, while I totally agree for figures meant to be seen by more people, when I'm just exploring the data I tend to not put any labels on anything, so I can see a use for having a `cbar` parameter (instead of doing `clabel=''` or `clabel=True`).

**Comment by MBravoS** [comment]
Working on #69 I tested fully switching to our colour bar function, but I think I ran into #41, as `plot_finalizer` switched to the colour bar axis and `clabel` wasn't working. Has that been fixed? If not, I would push against making it our default until the issue with returning the correct axis has been fixed.

As for the topic we left in the ear last year, did we have a final decision? At the moment I'm fine with the current functionality, and I still believe that passing a colour bar label should be enough to generate a color bar, but I'm not opposed to having a clearer option to _just_ invoke a colour bar.

**Comment by AstroRobin** [comment]
Not fixed yet as far as I remember, happy to use matplotlib colourbars for now as it should be easy enough to transition once we're happy our colourbars are foolproof.

I think I still prefer colourbar generation not being abstracted into the clabel. Even though it's more convenient, it almost seems like a hidden feature to new users. The middle ground perhaps is to have both a `cbar` (default=None) and `clabel` parameter. if cbar is True: make colourbar no matter what. if clabel is not None: make colourbar, but only if cbar is not False.

^ Maybe niche, but the reason you might set cbar = False and also give a clabel is when messing around with a plot and you want to quickly see it without the colourbar, which currently would require removing your clabel string. It might be a very complicated Latex equation that you don't want to retype — sure you could comment it out, but that's poor design by us.

**Comment by MBravoS** [comment]
Fair enough, and I like that middle point. I think that changing from `if clabel is not None` to `if cbar or (clabel and (cbar is None or cbar))` should do the trick.

**Comment by MBravoS** [comment]
It also ran the Examples notebook without issues, so I've set it as default for all `plots_2d` functions as of v0.6.2.0
