### ISSUE TITLE
Add an orientation parameter in hist

### ISSUE THREAD

**Issue by AstroRobin** [MBravoS/splotch#68]
Matplotlib's hist function has an orientation parameter which allows the user to create vertically-oriented histograms, which would be quite useful to try to replicate in splotch.

**Comment by MBravoS** [comment]
This is something I've thought more than once, but not on a serious manner yet. It's certainly something that we should implement, but I think it's best to explore this and #60 (to use `matplotlib.pyplot.step` instead of the current kludge) together as one overhaul of plots_1d.hist.

**Comment by AstroRobin** [comment]
Yep, I agree it's worth revamping plots_1d.hist and it looks like we could make use of some of those additional features. I also think we need to overhaul how we specify parameters (such as colour and linewidths) so that they aren't so specific to the hist_type being used.

**Comment by AstroRobin** [comment]
Added as of latest push to devel branch. This is perhaps a breaking change for some edge cases but it seems to be working well in my base testing.

```
arr1 = np.random.normal(0.0,1.0,size=2500)
arr2 = np.random.normal(-1.0,0.5,size=2500)

fig, axes = plt.subplots(figsize=(8,16), ncols=2, nrows=6, squeeze=False)

for jj, orient in enumerate(['horizontal', 'vertical']):
    for ii, htype in enumerate(['line', 'bar', 'step', 'linefilled', 'barfilled', 'stepfilled']):
        hist([arr1, arr2], hist_type=htype, bins=np.linspace(-3, 3, 20), orientation=orient, ax=axes[ii, jj],
             linewidth=[1,2], color=('blue', 'red'), ec=('navy', 'maroon'))
        axes[ii, jj].text(0.9, 0.8, htype, transform=axes[ii, jj].transAxes, ha='right', fontsize=14)

fig.tight_layout()
plt.show()
```

![image](https://user-images.githubusercontent.com/17759175/199173014-1685d276-b821-43db-9307-c7330bc9bcdd.png)

**Comment by MBravoS** [comment]
It seems to work without issues. I've merged the changes into the master branch.
