### ISSUE TITLE
Refactor code to move import calls out of functions

### ISSUE THREAD

**Issue by MBravoS** [MBravoS/splotch#69]
For some reason that now escapes me, we wrote most (if not all) functions in splotch with import calls locally for each function instead of globally. Not only this is not standard practice, but changing it will make keeping track of what we are importing easier.

**Comment by AstroRobin** [comment]
I agree, this is a strange design choice that we have stuck with — happy to move towards global imports.

**Comment by MBravoS** [comment]
I already started work on the `dev` branch. Since this is not a small rework I assume this would push the version to v0.6.0, and folding in our long-promised addition of [scicm](https://github.com/MBravoS/scicm) as the default colour map for splotch should be straightforward (it's what we have written in our README anyways). Now, I'm thinking if we should also fold the rework of `plots_1d.hist()` into v0.6.0 (see #60 and #68) or if it's better to keep the two separated. What do you think @AstroRobin?

**Comment by AstroRobin** [comment]
That sounds like a plan for the import rework. I do think we should perhaps keep the hist modifications separate however.

**Comment by MBravoS** [comment]
Ok, I have a working version on the devel branch. Could you check if it works for you @AstroRobin? I had to do more changes than expected, and while the Examples notebook runs (with small updates), there may be some edge case-scenario that I'm missing.

**Comment by AstroRobin** [comment]
I've had a look over most functions and they seem to be working now. Had to add a few missing imports in the last commit.

**Comment by AstroRobin** [comment]
Actually, I've found a few more missing imports over the last few commits, shouldn't be many left now...

**Comment by MBravoS** [comment]
Thanks. I haven't found anything else breaking as of v0.6.2.0, so I'll close the issue.
