### ISSUE TITLE
curve() fails to automatically generate labels when function given to expr

### ISSUE THREAD

**Issue by AstroRobin** [MBravoS/splotch#76]
The `expr` variable can either accept a string mathematical expression parsed by sympy or a python function or lambda. If the latter case is given without a label, the function tries (and fails) to fashion a default label out of the function, which it thinks is a string. Just need to catch these uses and decide what label option is best by default when giving a function/lambda.

**Comment by MBravoS** [comment]
Is there any easy way to extract a sensible label from a function, be it regular or anonymous? I would naively expect the answer to be no, so I would guess that the best option then is to raise a `ValueError` stating that a label it needs to be explicitly provided if the user wants one.

**Comment by AstroRobin** [comment]
Instead of a ValueError, I simply implemented an automatic label which looks at the name of the (regular) function and parameter names (regular and anonymous) to generate a somewhat sensible label. Had to make some changes to curve_piecewise() to make this work, but seems to be runnning.
