### ISSUE TITLE
Import practices

### ISSUE THREAD

**Issue by MBravoS** [MBravoS/splotch#8]
Might be worth looking into changing how we import things in our wrapper functions, from complete imports (i.e. `import matplotlib.pyplot as plt`) to just importing the required functions (i.e. `from matplotlib.pyplot import legend,plot`).

**Comment by MBravoS** [comment]
Work on this started in 0.2.7.0

**Comment by AstroRobin** [comment]
Implemented for plots_1d and plots_2d functions in 0.3.1.2.
